name: deploy-app
on:
  push:
    branches:
      - main
jobs:
  deploy:
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      users: actions/checkout@v3

    - name: simulate deployment
      run: echo "Deploying application"
