name: Python Setup

on:
  push:
    branches:
      - '**'

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # use quotes to ensure test script compatibility

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      - name: Check Python version
        run: python --version

      - name: Verify flake8 installation
        run: flake8 --version

      - name: Verify pytest installation
        run: pytest --version
